[project]
name = "myproject"
version = "0.1"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["models", "dataset", "studies", "utils"]
exclude = ["notebooks", "data", "config_files"]