# example config for training

# data paths
checkpoints_dir: "/home/cfoley_waller/defocam/defocuscamdata/models"
psf_dir: "/home/cfoley_waller/defocam/defocuscamdata/calibration_data/DMM_37UX178_ML_calib_data/11_21/multipos/alignment_psfs_telecent25um_5_blur/dim768-256_5focus"
base_data_path: "/home/cfoley_waller/10tb_extension/defocam/defocuscamdata/sample_data_preprocessed/sample_data_preprocessed_lri_02_02_no_adjoint"
false_color_mat_path: "/home/cfoley_waller/defocam/SpectralDefocusCam/utils/false_color_calib.mat"
mask_dir: "/home/cfoley_waller/defocam/defocuscamdata/calibration_data/DMM_37UX178_ML_calib_data/calib_matrix_11_10_2023_2_preprocessed/calibration_matrix_450-810_30chan_stride12_avg12.mat"

# model params
device: 0
data_precomputed: True
forward_model_params:
  stack_depth: 5
  psf:
    lri: True
    stride: 1
    symmetric: True
    optimize: False
    padded_shape: 768 #only used if LRI is False
    largest_psf_diam: 128
    exposures: [0.00151, 0.00909, 0.02222, 0.03333, 0.04761] # exposures of eahc psf level
  operations:
    sim_blur: False
    sim_meas: True
    adjoint: False
    spectral_pad: False
    roll: True
  
recon_model_params:
  model_name: "unet2d" # "r2attunet"
  spectral_depth: 30

# training params
epochs: 500
batch_size: 2
patch_size: [256, 256] # inference & training size (NOTE: downsampling reduces filter precision)
patch_crop: [768, 768] # actual size on camera
image_center: [1000, 2000] # center of both the image and mask crops
num_workers: 6
data_partition: [0.7, 0.15, 0.15] #["fruit", "pavia", "harvard"] # train, val, test
early_stopping_patience: 35
loss_function: 
  name: "mse" # mse, mae, cossim, lpips, psnr, ssim
  params: 
optimizer: 
  name: "adam" # adam, sgd, adagrad, rmsprop
  params: # kwargs
    lr: 0.0002
    # weight_decay: 0.002
lr_scheduler: 
  name: "exponential" # warm_cosine_anneal, exponential, plateau
  params: 
    gamma: 0.98

# restarting from checkpoint
preload_weights: True
checkpoint_dir: "/home/cfoley_waller/defocam/defocuscamdata/models/checkpoint_train_11_21_2023_lri_no_adjoint_2d_unet.yml/2024_02_02_21_44_52/saved_model_ep297_testloss_0.11502785682086906.pt"
offset: 297

# other params
log_grads: False
validation_stride: 3
checkpoint_stride: 9