# ------------------------------------------ #
# -------------- DO NOT CHANGE ------------- #
# -- STATIC CONFIG FOR FIGURE GENERATION --- #
# ------------------------------------------ #

# data paths
checkpoint_dir: "../../../data/models/checkpoint_train_02_07_2024_lsi_adjoint_condunet_L1psf_1meas_sharp.yml/2024_03_12_07_10_42/saved_model_ep5_testloss_0.06585123277497741.pt"
psf_dir: "../../../data/calibration_data/lsi_psfs_raw"
base_data_path: "../../../data/sample_data_preprocessed/model_ablation_test_set"
save_recon_path: "outputs/focused_lens_learned/"
mask_dir: "../../../data/calibration_data/calibration_matrix_390-870_30chan_stride16_avg16.mat"

# model params
device: 0
data_precomputed: False
forward_model_params:
  stack_depth: 1
  psf:
    lri: False
    stride: 1
    symmetric: True
    optimize: False
    padded_shape: 768 # only used if LRI is False
    largest_psf_diam: 128
    exposures: [0.00151] # exposures of eahc psf level
    threshold: 0.55 # noise threshold
    norm: one # applies normalization to each psf ("one": L1, "two": L2)
  operations:
    sim_blur: False
    sim_meas: True
    adjoint: False
    spectral_pad: False
    fwd_mask_noise: true
    shot_noise: true
    read_noise: true
  mask_noise:
    type: gaussian
    intensity: 0.001 # STD of gaussian calibration noise (we expect much more than sample)
  sample_noise:
    intensity: 0.001 # STD of gaussian read noise
    photon_count: 10000 # photon count for shot noise

recon_model_params:
  model_name: "unet_conditioned"
  norm: "local_response"
  
# training params
epochs: 100
batch_size: 3
grad_accumulate: 4
patch_size: [256, 256] # inference & training size (NOTE: downsampling reduces filter precision)
patch_crop: [768, 768] # actual size on camera
image_center: [1000, 2000] # center of both the image and mask crops
num_workers: 6
data_partition: [0.7, 0.15, 0.15] #["fruit", "pavia", "harvard"] # train, val, test
early_stopping_patience: 50
loss_function: 
  name: "mse" # mse, mae, cossim, lpips, psnr, ssim
  params: 
optimizer: 
  name: "adam" # adam, sgd, adagrad, rmsprop
  params: # kwargs
    lr: 0.0002
    weight_decay: 0.001
lr_scheduler: 
  name: "exponential" # warm_cosine_anneal, exponential, plateau
  params: 
    gamma: 0.98

# restarting from checkpoint
preload_weights: True
offset: 6

# other params
no_graph: True
log_grads: False
validation_stride: 1
checkpoint_stride: 1