# Template config file for inference

# data paths
weights: ["your/weights/here1.pt", "your/weights/here2.pt", "your/weights/here3.pt"]

#inference params
prelim_metric: "mse" # mae, mse, cossim, lpips, psnr, ssim
num_workers: 4
device: "cpu"