# example config for training

# data paths
checkpoints_dir: "checkpoints/dir/here"
psf_dir: "psfs/dir/here" # unused if sim_blur = True
base_data_path: "data/dir/here"
false_color_mat_path: "data/dir/here"

# model params
device: 2
forward_model_params:
  stack_depth: 3
  sim_blur: True
  optimize_blur: False
  blur_type: "symmetric"
recon_model_params:
  model_name: "unet" #"lcnf"
  # unet params

  # lcnf params
  encoder_specs:
    name: edsr
    args: 
      no_upsampling: True
      input_channel: 30
  imnet_spec:
    name: mlp
    args:
      out_dim: 30
      hidden_list: [256, 256, 256, 256, 256]
  enhancements:
    local_ensemble: True
    feat_unfold: True
    cell_decode: True
    radialencode: False
    encoord_dim: 48
    angle_num: 12

# training params
epochs: 2
batch_size: 16
data_partition: [0.85,0.15,0] #train,val,test
early_stopping_patience: 10
checkpoint_stride: 15
loss_function: 
  name: "mse" # mse, mae, cossim, lpips, psnr, ssim
  params: 
optimizer: 
  name: "adam" #adam, sgd, adagrad, rmsprop
  params: #kwargs
    lr: 0.0008
    weight_decay: 0.01
    momentum: 0.8
lr_scheduler: 
  name: "warm_cosine_anneal" # exponential, plateau
  params: 
    T_0: 30
    T_mult: 1.1

# restarting from checkpoint
preload_weights: False
checkpoint_dir: "your/weights/here.pt"
offset: 0