# training config — cleaned and reformatted

# data paths
checkpoint_dir: "/home/cfoley/defocuscamdata/models/checkpoint_train_02_07_2024_lsi_adjoint_condunet_firstlastonly_L1psf_3meas.yml/2024_03_20_00_38_33/saved_model_ep68_testloss_0.039786975884608014.pt"
config_fname: "/home/cfoley/SpectralDefocusCam/config_files/cond_unet_ablation/train_02_07_2024_lsi_adjoint_condunet_firstlastonly_L1psf_3meas.yml"
base_data_path: "/home/cfoley/defocuscamdata/sample_data_preprocessed/sample_data_preprocessed_lsi_02_07_L1psf_3meas"
psf_dir: "/home/cfoley/defocuscamdata/calibration_data/DMM_37UX178_ML_calib_data/11_21/singlepos/psfs_ONAXIS_telecent25um"
mask_dir: "/home/cfoley/defocuscamdata/calibration_data/DMM_37UX178_ML_calib_data/calib_matrix_2_23_2024_processed/calibration_matrix_L1_390-870_30chan_stride16_avg16.mat"

# model params
device: 2
data_precomputed: false
forward_model_params:
  stack_depth: 3
  psf:
    lri: false
    stride: 2
    symmetric: true
    optimize: false
    padded_shape: [768, 768]
    largest_psf_diam: 128
    exposures: [0.00151, 0.02222, 0.04761]
    threshold: 0.55
    norm: one
  operations:
    sim_blur: false
    sim_meas: true
    adjoint: false  # conditional unets have the adjoint operation built in
    spectral_pad: false
    adj_mask_noise: false
    fwd_mask_noise: true
    shot_noise: true
    read_noise: true
  mask_noise:
    type: gaussian
    intensity: 0.001 # STD of gaussian calibration noise (we expect much more than sample)
  sample_noise:
    intensity: 0.001 # STD of gaussian read noise
    photon_count: 10000 # photon count for shot noise

recon_model_params:
  model_name: "unet_conditioned"
  num_measurements: 3
  condition_first_last: true
  blur_stride: 2
  norm: local_response

# training params
epochs: 70
batch_size: 4
grad_accumulate: 2
patch_size: [256, 256] # inference & training size (NOTE: downsampling reduces filter precision)
patch_crop: [768, 768] # actual size on camera
image_center: [1000, 2000] # center of both the image and mask crops
num_workers: 6
data_partition: [0.7, 0.15, 0.15] #["fruit", "pavia", "harvard"] # train, val, test
early_stopping_patience: 50

loss_function: 
  name: "mse" # mse, mae, cossim, lpips, psnr, ssim
  params: 

optimizer: 
  name: "adam" # adam, sgd, adagrad, rmsprop
  params: # kwargs
    lr: 0.000005
    weight_decay: 0.001
    
lr_scheduler: 
  name: "exponential" # warm_cosine_anneal, exponential, plateau
  params: 
    gamma: 0.94

# restarting from checkpoint
preload_weights: True
offset: 61

# other params
no_graph: True
log_grads: False
validation_stride: 1
checkpoint_stride: 1
