# example config for training

# data paths
checkpoints_dir: "/home/cfoley/defocuscamdata/models"
psf_dir: "/home/cfoley/defocuscamdata/calibration_data/DMM_37UX178_ML_calib_data/11_21/singlepos/psfs_ONAXIS_telecent25um"
base_data_path: "/home/cfoley/defocuscamdata/sample_data_preprocessed/patch_predict/sample_data_preprocessed_lrnd_patch3_lsi_02_07_L1psf_2meas"
mask_dir: "/home/cfoley/defocuscamdata/calibration_data/DMM_37UX178_ML_calib_data/calib_matrix_2_23_2024_processed/calibration_matrix_L1_390-870_30chan_stride16_avg16.mat"

# model params
device: 1
data_precomputed: True
passthrough: True
forward_model_params:
  stack_depth: 2
  psf:
    lri: False
    stride: 4
    symmetric: True
    optimize: False
    padded_shape: 768 # only used if LRI is False
    largest_psf_diam: 128
    exposures: [0.00151, 0.04761] # exposures of eahc psf level
    threshold: 0.55 # noise threshold
    norm: one # applies normalization to each psf ("one": L1, "two": L2)
  operations:
    sim_blur: False
    sim_meas: True
    adjoint: False
    spectral_pad: False
    adj_mask_noise: False
    fwd_mask_noise: True
  mask_noise: # augment mask with noise
    intensity: [0, 0.03]
    stopband_only: true
    type: gaussian
  
recon_model_params:
  model_name: "unet_conditioned"
  norm: "local_response"
  
# training params
epochs: 25
batch_size: 4
grad_accumulate: 2
patch_size: [256, 256] # inference & training size (NOTE: downsampling reduces filter precision)
patch_crop: [768, 768] # actual size on camera
image_center: [954, 2516] # center of both the image and mask crops
num_workers: 6
data_partition: [0.7, 0.15, 0.15] #["fruit", "pavia", "harvard"] # train, val, test
early_stopping_patience: 20
loss_function: 
  name: "mse" # mse, mae, cossim, lpips, psnr, ssim
  params: 
optimizer: 
  name: "adam" # adam, sgd, adagrad, rmsprop
  params: # kwargs
    lr: 0.00015
    weight_decay: 0.001
lr_scheduler: 
  name: "exponential" # warm_cosine_anneal, exponential, plateau
  params: 
    gamma: 0.92

# restarting from checkpoint
preload_weights: True
checkpoint_dir: "/home/cfoley/defocuscamdata/models/checkpoint_results_learned_patch3_config.yml/2024_03_15_14_51_27/saved_model_ep14_testloss_0.08418937435127655.pt"
offset: 15

# other params
no_graph: True
log_grads: False
validation_stride: 1
checkpoint_stride: 1